#ifndef __UI_H__
#define __UI_H__

//PIC
#define Img_1_1           1
#define Img_1_2           2
#define Img_1_3           3
#define Img_1_4           4
#define Img_1_5           5
#define Img_1_6           6
#define Img_1_7           7
#define Img_1_9           8
#define Img_1_10          9
#define Img_1_11          10
#define Img_1_12          11
#define Img_1_13          12
#define Img_1_15          13
#define Img_1_16          14
#define Img_1_17          15
#define Img_1_18          16
#define Img_1_19          17
#define Img_1_20          18
#define Img_1_21          19
#define Img_1_22          20
#define Img_1_23          21
#define Img_1_25          22
#define Img_1_26          23
#define Img_1_27          24
#define Img_1_28          25
#define Img_1_30          26
#define Img_1_33          27
#define Img_1_40          28
#define Img_1_41          29
#define Img_1_42          30
#define Img_1_43          31
#define Img_1_44          32
#define Img_1_45          33
#define Img_1_46          34
#define Img_1_47          35
#define Img_1_48          36
#define Img_1_49          37
#define Img_1_50          38
#define Img_2_1           39
#define Img_2_2           40
#define Img_2_3           41
#define Img_2_4           42
#define Img_2_5           43
#define Img_2_6           44
#define Img_2_7           45
#define Img_2_8           46
#define Img_2_9           47
#define Img_2_10          48
#define Img_2_11          49
#define Img_2_12          50
#define Img_2_13          51
#define Img_3_1           52
#define Img_3_2           53
#define Img_3_3           54
#define Img_3_4           55
#define Img_3_5           56
#define Img_3_6           57
#define Img_3_7           58
#define Img_4_1           59
#define Img_4_2           60
#define Img_4_3           61
#define Img_4_4           62
#define Img_4_5           63
#define Img_4_6           64
#define Img_4_7           65
#define Img_4_8           66
#define Img_4_9           67
#define Img_4_10          68
#define Img_4_11          69
#define Img_4_12          70
#define Img_4_13          71
#define Img_4_14          72
#define Img_4_15          73
#define Img_4_16          74

//TEXT
#define Txt_1_1           1
#define Txt_1_2           2
#define Txt_1_3           3
#define Txt_1_4           4
#define Txt_1_5           5
#define Txt_3_1           6
#define Txt_3_2           7
#define Txt_3_3           8
#define Txt_4_1           9
#define Txt_4_2           10
#define Txt_4_3           11
#define Txt_4_4           12
#define Txt_4_5           13

//TIME
#define Time_3_1          1
#define Time_3_2          2
#define Time_3_3          3
#define Time_3_4          4
#define Time_4_1          5

//MENU
#define Menu_2_1          1
#define Menu_2_2          2

//NUMBER
#define Number_1_1        1
#define Number_3_1        2
#define Number_3_2        3
#define Number_3_3        4
#define Number_3_4        5
#define Number_3_5        6
#define Number_3_6        7

//MOVE

//PROGRESS

//RADIO

//CHECK

//BUTTON

//REGION

//LAYER
#define Layer_1_1         1
#define Layer_1_2         2
#define Layer_1_3         3
#define Layer_2_3         4
#define Layer_3_2         5
#define Layer_3_3         6
#define Layer_4_1         7
#define Layer_4_2         8


#endif
