#ifndef __USB_INC_H__
#define __USB_INC_H__
#include "dv12.h"


#define HUSB_FADDR         ((volatile u8  *)(husb_base + 0x000))
#define HUSB_POWER         ((volatile u8  *)(husb_base + 0x001))
#define HUSB_INTRTX        ((volatile u16 *)(husb_base + 0x002))
#define HUSB_INTRRX        ((volatile u16 *)(husb_base + 0x004))
#define HUSB_INTRTXE       ((volatile u16 *)(husb_base + 0x006))
#define HUSB_INTRRXE       ((volatile u16 *)(husb_base + 0x008))
#define HUSB_INTRUSB       ((volatile u8  *)(husb_base + 0x00a))
#define HUSB_INTRUSBE      ((volatile u8  *)(husb_base + 0x00b))
#define HUSB_FRAME         ((volatile u16 *)(husb_base + 0x00c))
#define HUSB_INDEX         ((volatile u8  *)(husb_base + 0x00e))
#define HUSB_TESTMODE      ((volatile u8  *)(husb_base + 0x00f))

#define HUSB_FIFO0         ((volatile u8  *)(husb_base + 0x020))
#define HUSB_FIFO1         ((volatile u8  *)(husb_base + 0x024))
#define HUSB_FIFO2         ((volatile u8  *)(husb_base + 0x028))
#define HUSB_FIFO3         ((volatile u8  *)(husb_base + 0x02c))
#define HUSB_FIFO4         ((volatile u8  *)(husb_base + 0x030))
#define HUSB_DEVCTL        ((volatile u8  *)(husb_base + 0x060))

#define HUSB_CSR0          ((volatile u16 *)(husb_base + 0x102))
#define HUSB_COUNT0        ((volatile u16 *)(husb_base + 0x108))
#define HUSB_NAKLIMIT0     ((volatile u8  *)(husb_base + 0x10b))
#define HUSB_CFGDATA       ((volatile u8  *)(husb_base + 0x10f))

#define HUSB_EP1TXMAXP     ((volatile u16 *)(husb_base + 0x110))
#define HUSB_EP1TXCSR      ((volatile u16 *)(husb_base + 0x112))
#define HUSB_EP1RXMAXP     ((volatile u16 *)(husb_base + 0x114))
#define HUSB_EP1RXCSR      ((volatile u16 *)(husb_base + 0x116))
#define HUSB_EP1RXCOUNT    ((volatile u16 *)(husb_base + 0x118))
#define HUSB_EP1TXTYPE     ((volatile u8  *)(husb_base + 0x11a))
#define HUSB_EP1TXINTERVAL ((volatile u8  *)(husb_base + 0x11b))
#define HUSB_EP1RXTYPE     ((volatile u8  *)(husb_base + 0x11c))
#define HUSB_EP1RXINTERVAL ((volatile u8  *)(husb_base + 0x11d))
#define HUSB_EP1FIFOSIZE   ((volatile u8  *)(husb_base + 0x11f))
         
#define HUSB_EP2TXMAXP     ((volatile u16 *)(husb_base + 0x120))
#define HUSB_EP2TXCSR      ((volatile u16 *)(husb_base + 0x122))
#define HUSB_EP2RXMAXP     ((volatile u16 *)(husb_base + 0x124))
#define HUSB_EP2RXCSR      ((volatile u16 *)(husb_base + 0x126))
#define HUSB_EP2RXCOUNT    ((volatile u16 *)(husb_base + 0x128))
#define HUSB_EP2TXTYPE     ((volatile u8  *)(husb_base + 0x12a))
#define HUSB_EP2TXINTERVAL ((volatile u8  *)(husb_base + 0x12b))
#define HUSB_EP2RXTYPE     ((volatile u8  *)(husb_base + 0x12c))
#define HUSB_EP2RXINTERVAL ((volatile u8  *)(husb_base + 0x12d))
#define HUSB_EP2FIFOSIZE   ((volatile u8  *)(husb_base + 0x12f))
         
#define HUSB_EP3TXMAXP     ((volatile u16 *)(husb_base + 0x130))
#define HUSB_EP3TXCSR      ((volatile u16 *)(husb_base + 0x132))
#define HUSB_EP3RXMAXP     ((volatile u16 *)(husb_base + 0x134))
#define HUSB_EP3RXCSR      ((volatile u16 *)(husb_base + 0x136))
#define HUSB_EP3RXCOUNT    ((volatile u16 *)(husb_base + 0x138))
#define HUSB_EP3TXTYPE     ((volatile u8  *)(husb_base + 0x13a))
#define HUSB_EP3TXINTERVAL ((volatile u8  *)(husb_base + 0x13b))
#define HUSB_EP3RXTYPE     ((volatile u8  *)(husb_base + 0x13c))
#define HUSB_EP3RXINTERVAL ((volatile u8  *)(husb_base + 0x13d))
#define HUSB_EP3FIFOSIZE   ((volatile u8  *)(husb_base + 0x13f))
         
#define HUSB_EP4TXMAXP     ((volatile u16 *)(husb_base + 0x140))
#define HUSB_EP4TXCSR      ((volatile u16 *)(husb_base + 0x142))
#define HUSB_EP4RXMAXP     ((volatile u16 *)(husb_base + 0x144))
#define HUSB_EP4RXCSR      ((volatile u16 *)(husb_base + 0x146))
#define HUSB_EP4RXCOUNT    ((volatile u16 *)(husb_base + 0x148))
#define HUSB_EP4TXTYPE     ((volatile u8  *)(husb_base + 0x14a))
#define HUSB_EP4TXINTERVAL ((volatile u8  *)(husb_base + 0x14b))
#define HUSB_EP4RXTYPE     ((volatile u8  *)(husb_base + 0x14c))
#define HUSB_EP4RXINTERVAL ((volatile u8  *)(husb_base + 0x14d))
#define HUSB_EP4FIFOSIZE   ((volatile u8  *)(husb_base + 0x14f))

#endif
