#ifndef __UI_H__
#define __UI_H__

//PIC
#define Img_1_1           1
#define Img_1_2           2
#define Img_1_3           3
#define Img_1_4           4
#define Img_1_5           5
#define Img_1_6           6
#define Img_1_7           7
#define Img_1_8           8
#define Img_1_9           9
#define Img_1_10          10
#define Img_1_11          11
#define Img_1_12          12
#define Img_1_13          13
#define Img_1_14          14
#define Img_1_15          15
#define Img_1_16          16
#define Img_1_17          17
#define Img_1_18          18
#define Img_1_19          19
#define Img_1_20          20
#define Img_1_21          21
#define Img_1_22          22
#define Img_2_1           23
#define Img_2_2           24
#define Img_2_3           25
#define Img_2_4           26
#define Img_3_1           27
#define Img_3_2           28
#define Img_3_3           29
#define Img_3_4           30
#define Img_3_5           31
#define Img_3_6           32
#define Img_3_7           33
#define Img_4_1           34
#define Img_4_2           35
#define Img_4_3           36
#define Img_4_7           37
#define Img_4_8           38
#define Img_4_4           39
#define Img_4_5           40

//TEXT
#define Txt_3_1           1
#define Txt_4_1           2
#define Txt_4_2           3

//TIME
#define Time_3_1          1
#define Time_3_2          2

//MENU
#define Menu_2_1          1

//NUMBER
#define Number_3_2        1
#define Number_3_3        2
#define Number_3_4        3
#define Number_3_5        4
#define Number_3_6        5
#define Number_3_1        6

//MOVE

//PROGRESS

//RADIO

//CHECK

//BUTTON

//LAYER
#define Layer_1_1         1
#define Layer_1_2         2
#define Layer_1_3         3
#define Layer_2_2         4


#endif
