#ifndef __UIIMG_H__
#define __UIIMG_H__

//LAYER_IMAGE
#define LayerJpg   BACK
#define LayerJpg   BACK1

//LAYER_OSD
#define LayerBmp   png1
#define LayerBmp   png6
#define LayerBmp   PNG25
#define LayerBmp   PNG13
#define LayerBmp   PNG16
#define LayerBmp   PNG35
#define LayerBmp   PNG15
#define LayerBmp   PNG17
#define LayerBmp   PNG26
#define LayerBmp   PNG37
#define LayerBmp   M160
#define LayerBmp   M161
#define LayerBmp   M162
#define LayerBmp   M163
#define LayerBmp   png36
#define LayerBmp   png11
#define LayerBmp   PNG14
#define LayerBmp   PNG12A
#define LayerBmp   PNG12
#define LayerBmp   png48
#define LayerBmp   PNG7
#define LayerBmp   PNG4
#define LayerBmp   PNG5
#define LayerBmp   png10
#define LayerBmp   A0026JL
#define LayerBmp   A0022JL
#define LayerBmp   A0023JL
#define LayerBmp   
#define LayerBmp   A0004JL
#define LayerBmp   A0003JL
#define LayerBmp   A0008JL
#define LayerBmp   PNG8
#define LayerBmp   png41
#define LayerBmp   PNG42
#define LayerBmp   png47
#define LayerBmp   VER
#define LayerBmp   MSG_BACK
#define LayerBmp   MSG_BACK2
#define LayerBmp   NUM0
#define LayerBmp   NUM1
#define LayerBmp   NUM2
#define LayerBmp   NUM3
#define LayerBmp   NUM4
#define LayerBmp   NUM5
#define LayerBmp   NUM6
#define LayerBmp   NUM7
#define LayerBmp   NUM8
#define LayerBmp   NUM9
#define LayerBmp   NUM11
#define LayerBmp   A0020JL
#define LayerBmp   N0
#define LayerBmp   N1
#define LayerBmp   N2
#define LayerBmp   N3
#define LayerBmp   N4
#define LayerBmp   N5
#define LayerBmp   N6
#define LayerBmp   N7
#define LayerBmp   N8
#define LayerBmp   N9
#define LayerBmp   N10
#define LayerBmp   N11
#define LayerBmp   PNG28
#define LayerBmp   PNG29
#define LayerBmp   PNG30
#define LayerBmp   PNG31
#define LayerBmp   png34
#define LayerBmp   PNG32
#define LayerBmp   PNG33

#endif
