//generated by ResBuilder in 2014//
#ifndef _RES_H_  
#define _RES_H_  

////StringResID Define Table////
#define  Chinese_Simplified       1   //简体中文
#define  Chinese_Traditional      2   //繁体中文
#define  Japanese                 3   //日语
#define  Korean                   4   //韩语
#define  English                  5   //英语
#define  French                   6   //法语
#define  German                   7   //德语
#define  Italian                  8   //意大利语
#define  Dutch                    9   //荷兰语
#define  Portuguese               10  //葡萄牙语
#define  Spanish                  11  //西班牙语
#define  Swedish                  12  //瑞典语
#define  Czech                    13  //捷克语
#define  Danish                   14  //丹麦语
#define  Polish                   15  //波兰语
#define  Russian                  16  //俄语
#define  Turkey                   17  //土耳其语
#define  Hebrew                   18  //希伯来语
#define  Thai                     19  //泰语
#define  Hungarian                20  //匈牙利语
#define  Romanian                 21  //罗马尼亚语
#define  Arabic                   22  //阿拉伯语

#define  LANGUAGEID_SUM           22

////BmpResID Define Table////
#define  A0001JL                  1
#define  A0002JL                  2
#define  A0003JL                  3
#define  A0004JL                  4
#define  A0005JL                  5
#define  A0006JL                  6
#define  A0007JL                  7
#define  A0008JL                  8
#define  A0009JL                  9
#define  A0010JL0                 10
#define  A0010JL1                 11
#define  A0010JL2                 12
#define  A0010JL3                 13
#define  A0010JL4                 14
#define  A0010JL5                 15
#define  A0010JL6                 16
#define  A0010JL7                 17
#define  A0010JL8                 18
#define  A0010JL9                 19
#define  A0020JL                  20
#define  A0021JL                  21
#define  A0022JL                  22
#define  A0023JL                  23
#define  A0024JL                  24
#define  A0025JL                  25
#define  A0026JL                  26
#define  A0027JL                  27
#define  A0028JL                  28
#define  A0029JL                  29
#define  A0030JL                  30
#define  A0031JL                  31
#define  ASTERN                   32
#define  BACK                     33
#define  BACK1                    34
#define  CLEAR                    35
#define  CLOSE                    36
#define  CLOSE1                   37
#define  MENU_P                   38
#define  MEN_BAC                  39
#define  MEN_SEL                  40
#define  MEN_USEL                 41
#define  MSG_BACK                 42
#define  MSG_BACK2                43
#define  MSG_BACK3                44
#define  N0                       45
#define  N1                       46
#define  N2                       47
#define  N3                       48
#define  N4                       49
#define  N5                       50
#define  N6                       51
#define  N7                       52
#define  N8                       53
#define  N9                       54
#define  N10                      55
#define  N11                      56
#define  NEXT                     57
#define  NUM0                     58
#define  NUM1                     59
#define  NUM2                     60
#define  NUM3                     61
#define  NUM4                     62
#define  NUM5                     63
#define  NUM6                     64
#define  NUM7                     65
#define  NUM8                     66
#define  NUM9                     67
#define  NUM10                    68
#define  NUM11                    69
#define  NUM12                    70
#define  ON_SEL_B                 71
#define  ON_SEL_W                 72
#define  OPEN                     73
#define  P12                      74
#define  P13                      75
#define  P14                      76
#define  P15                      77
#define  P16                      78
#define  P17                      79
#define  P18                      80
#define  P19                      81
#define  P20                      82
#define  P21                      83
#define  P22                      84
#define  P23                      85
#define  P24                      86
#define  P25                      87
#define  P26                      88
#define  P27                      89
#define  P28                      90
#define  P29                      91
#define  P30                      92
#define  P31                      93
#define  P32                      94
#define  P34                      95
#define  P35                      96
#define  P36                      97
#define  P37                      98
#define  P38                      99
#define  P39                      100
#define  P40                      101
#define  P41                      102
#define  P42                      103
#define  P43                      104
#define  P44                      105
#define  P45                      106
#define  P46                      107
#define  P47                      108
#define  P48                      109
#define  P52                      110
#define  P53                      111
#define  P54                      112
#define  P55                      113
#define  P56                      114
#define  P57                      115
#define  P58                      116
#define  P59                      117
#define  P60                      118
#define  P61                      119
#define  P62                      120
#define  P63                      121
#define  P64                      122
#define  P65                      123
#define  P66                      124
#define  P67                      125
#define  P68                      126
#define  P69                      127
#define  P70                      128
#define  P71                      129
#define  P72                      130
#define  P73                      131
#define  P74                      132
#define  P75                      133
#define  P76                      134
#define  P77                      135
#define  P78                      136
#define  P79                      137
#define  P80                      138
#define  P81                      139
#define  P82                      140
#define  P83                      141
#define  P84                      142
#define  P85                      143
#define  P86                      144
#define  P87                      145
#define  P88                      146
#define  P89                      147
#define  P90                      148
#define  P91                      149
#define  P92                      150
#define  P93                      151
#define  P94                      152
#define  P95                      153
#define  P96                      154
#define  P97                      155
#define  P98                      156
#define  P99                      157
#define  P100                     158
#define  P101                     159
#define  P102                     160
#define  P103                     161
#define  P104                     162
#define  P105                     163
#define  P106                     164
#define  P107                     165
#define  P108                     166
#define  P109                     167
#define  P110                     168
#define  PC_CAM                   169
#define  PNG1                     170
#define  PNG2                     171
#define  PNG3                     172
#define  PNG4                     173
#define  PNG5                     174
#define  PNG6                     175
#define  PNG7                     176
#define  PNG8                     177
#define  PNG9                     178
#define  PNG10                    179
#define  PNG11                    180
#define  PNG12                    181
#define  PNG12A                   182
#define  PNG13                    183
#define  PNG14                    184
#define  PNG14A                   185
#define  PNG15                    186
#define  PNG15A                   187
#define  PNG15B                   188
#define  PNG16                    189
#define  PNG17                    190
#define  PNG18                    191
#define  PNG19                    192
#define  PNG20                    193
#define  PNG21                    194
#define  PNG22                    195
#define  PNG23                    196
#define  PNG24                    197
#define  PNG25                    198
#define  PNG26                    199
#define  PNG27                    200
#define  PNG28                    201
#define  PNG29                    202
#define  PNG30                    203
#define  PNG31                    204
#define  PNG32                    205
#define  PNG33                    206
#define  PNG34                    207
#define  PNG35                    208
#define  PNG36                    209
#define  PNG37                    210
#define  PNG38                    211
#define  PNG39                    212
#define  PNG40                    213
#define  PNG41                    214
#define  PNG42                    215
#define  PNG43                    216
#define  PNG44                    217
#define  PNG45                    218
#define  PNG46                    219
#define  PNG47                    220
#define  PNG48                    221
#define  PNG49                    222
#define  PNG50                    223
#define  PNG51                    224
#define  PNG52                    225
#define  PNG53                    226
#define  PNG54                    227
#define  PNG55                    228
#define  PNG56                    229
#define  PNG57                    230
#define  PNG58                    231
#define  PNG59                    232
#define  PNG60                    233
#define  PNG61                    234
#define  PNG67                    235
#define  PNG76                    236
#define  PNG79                    237
#define  PNG90                    238
#define  PNG91                    239
#define  PNG92                    240
#define  PNG93                    241
#define  PNG94                    242
#define  POWER_OFF_LOGO           243
#define  POWER_ON_LOGO            244
#define  PREVIEW                  245
#define  PWR_OFF                  246
#define  P_RESO                   247
#define  R_NUM0                   248
#define  R_NUM1                   249
#define  R_NUM2                   250
#define  R_NUM3                   251
#define  R_NUM4                   252
#define  R_NUM5                   253
#define  R_NUM6                   254
#define  R_NUM7                   255
#define  R_NUM8                   256
#define  R_NUM9                   257
#define  R_NUM10                  258
#define  R_NUM11                  259
#define  R_NUM12                  260
#define  SELE_FCS                 261
#define  SELE_UFCS                262
#define  SEL_ON                   263
#define  SEL_ONB                  264
#define  SETGROUND                265
#define  USB_MOD                  266
#define  VTL_LIGHT                267
#define  S13                      268 //目录播放
#define  S16                      269 //随机播放
#define  S28                      270 //录音模式
#define  M01                      271 //解析度
#define  M02                      272 //循环录像
#define  M03                      273 //曝光
#define  M04                      274 //移动侦测
#define  M05                      275 //录影音频
#define  M06                      276 //时间水印
#define  M07                      277 //视频
#define  M08                      278 //1080FHD
#define  M09                      279 //1080P
#define  M10                      280 //FHD
#define  M11                      281 //WVGA 848x480
#define  M12                      282 //HD
#define  M13                      283 //20160401 SZJL V2.0
#define  M14                      284 //关
#define  M15                      285 //1分钟
#define  M16                      286 //2分钟
#define  M17                      287 //3分钟
#define  M18                      288 //-3
#define  M19                      289 //-2
#define  M20                      290 //-1
#define  M21                      291 //0
#define  M22                      292 //1
#define  M23                      293 //2
#define  M24                      294 //3
#define  M25                      295 //-1/3
#define  M26                      296 //-2/3
#define  M27                      297 //-1.0
#define  M28                      298 //-4/3
#define  M29                      299 //-5/3
#define  M30                      300 //-2.0
#define  M31                      301 //开
#define  M32                      302 //关
#define  M33                      303 //拍照
#define  M34                      304 //拍摄方式
#define  M35                      305 //解析度
#define  M36                      306 //连拍
#define  M37                      307 //拍照质量
#define  M38                      308 //锐度
#define  M39                      309 //白平衡
#define  M40                      310 //色彩
#define  M41                      311 //ISO
#define  M42                      312 //曝光补偿
#define  M43                      313 //防手震
#define  M44                      314 //快速预览
#define  M45                      315 //日期标签
#define  M46                      316 //补光灯
#define  M47                      317 //电视制式
#define  M48                      318 //PAL
#define  M49                      319 //NTSC
#define  M50                      320 //12M 4032x3024
#define  M51                      321 //10M 3648x2738
#define  M52                      322 //8M
#define  M53                      323 //5M 
#define  M54                      324 //3M
#define  M55                      325 //2M
#define  M56                      326 //VGA 640x480
#define  M57                      327 //1.3M 1280x960
#define  M58                      328 //优质
#define  M59                      329 //标准
#define  M60                      330 //经济
#define  M61                      331 //强烈
#define  M62                      332 //标准
#define  M63                      333 //柔和
#define  M64                      334 //自动
#define  M65                      335 //日光
#define  M66                      336 //阴天
#define  M67                      337 //钨丝灯
#define  M68                      338 //荧光灯
#define  M69                      339 //无特效
#define  M70                      340 //黑白
#define  M71                      341 //怀旧
#define  M72                      342 //负片
#define  M73                      343 //曝晒
#define  M74                      344 //200
#define  M75                      345 //400
#define  M76                      346 //2秒
#define  M77                      347 //5秒
#define  M78                      348 //日期
#define  M79                      349 //日期/时间
#define  M80                      350 //回放
#define  M81                      351 //删除
#define  M82                      352 //保护
#define  M83                      353 //幻灯片播放
#define  M84                      354 //删除当前
#define  M85                      355 //全部删除
#define  M86                      356 //加锁当前
#define  M87                      357 //解锁当前
#define  M88                      358 //全部加锁
#define  M89                      359 //解锁全部
#define  M90                      360 //2秒
#define  M91                      361 //5秒
#define  M92                      362 //8秒
#define  M93                      363 //设置
#define  M94                      364 //日期/时间
#define  M95                      365 //自动关机
#define  M96                      366 //按键声音
#define  M97                      367 //语言
#define  M98                      368 //TV模式
#define  M99                      369 //光源频率
#define  M100                     370 //红外灯设定
#define  M101                     371 //影像旋转
#define  M102                     372 //屏幕保护
#define  M103                     373 //重力感应
#define  M104                     374 //设置
#define  M105                     375 //格式化
#define  M106                     376 //恢复出厂设置
#define  M107                     377 //固件版本
#define  M108                     378 //关
#define  M109                     379 //1分钟
#define  M110                     380 //3分钟
#define  M111                     381 //日本语
#define  M112                     382 //русский
#define  M113                     383 //繁体中文
#define  M114                     384 //简体中文
#define  M115                     385 //Italiano
#define  M116                     386 //Deutsch
#define  M117                     387 //Espanol
#define  M118                     388 //Francais
#define  M119                     389 //English
#define  M120                     390 //PAL
#define  M121                     391 //NTSC
#define  M122                     392 //50Hz
#define  M123                     393 //60Hz
#define  M124                     394 //关
#define  M125                     395 //自动
#define  M126                     396 //3分钟
#define  M127                     397 //5分钟
#define  M128                     398 //10分钟
#define  M129                     399 //高
#define  M130                     400 //中
#define  M131                     401 //低
#define  M132                     402 //内存
#define  M133                     403 //SD卡
#define  M134                     404 //开始录像
#define  M135                     405 //保存录像
#define  M136                     406 //存储器
#define  M137                     407 //PC摄像
#define  M138                     408 //USB
#define  M140                     409 //取消
#define  M141                     410 //确认
#define  M139                     411 //
#define  M142                     412 //恢复默认设置 
#define  M143                     413 //删除所有数据 
#define  M144                     414 //删除当前文件
#define  M145                     415 //删除所有文件
#define  M146                     416 //请稍候
#define  M147                     417 //提示
#define  M148                     418 //电量不足
#define  M149                     419 //没有文件
#define  M150                     420 //内存错误
#define  M151                     421 //存储器
#define  M152                     422 //未插入卡
#define  M153                     423 //存储器
#define  M154                     424 //存储空间不足
#define  M155                     425 //请格式化卡
#define  M156                     426 //请插入SD卡
#define  M157                     427 //取消
#define  M158                     428 //确认
#define  M159                     429 //正在删除文件...
#define  M160                     430 //1080P
#define  M161                     431 //720P
#define  M162                     432 //VGA
#define  M163                     433 //2M
#define  M164                     434 //正在恢复出厂设置
#define  M165                     435 //正在格式化…
#define  M166                     436 //正在删除全部文件…
#define  M167                     437 //10秒
#define  M168                     438 //20秒
#define  M169                     439 //30秒
#define  M170                     440 //1M
#define  M171                     441 //录像声音
#define  M172                     442 //停车监控
#define  M173                     443 //录像模式
#define  M174                     444 //坏损文件
#define  M175                     445 //常用设置
#define  M176                     446 //风格偏好
#define  M177                     447 //安全辅助
#define  M178                     448 //系统设置
#define  M179                     449 //确认后数据将丢失！
#define  M180                     450 //确认后将恢复出厂设置！
#define  M181                     451 //夜视增强
#define  M182                     452 //正在解锁全部文件
#define  M183                     453 //加锁文件过多,请解锁或格式化
#define  M184                     454 //不再保护录像文件
#define  M185                     455 //更改设置后需格式化
#define  M186                     456 //5s后自动关机
#define  M187                     457 //TF卡错误

#endif
